-- INSERTING INTO CHURCH TABLE
INSERT INTO CHURCH (NAME) VALUES ('PARÓQUIA SÃO JOAQUIM');

-- INSERTING INTO PROVING TYPE TABLE
INSERT INTO PROVING_TYPE (NAME, MNEMONIC) VALUES ('TALÃO', 'TLO');
INSERT INTO PROVING_TYPE (NAME, MNEMONIC) VALUES ('SEM COMPROVANTE', 'SCT');
