###
#   Database Settings
###
spring:
  datasource:
    url: ${datasource.url}
    platform: ${datasource.platform}
    username: ${datasource.username}
    password: ${datasource.password}
    driverClassName: ${datasource.driver}
  jpa:
    database-platform: ${jpa.database.platform}
    hibernate:
      ddl-auto: ${jpa.hibernate.dll.auto}
    properties:
      hibernate:
        show_sql: ${jpa.properties.hibernate.show_sql}
        use_sql_comments: ${jpa.properties.hibernate.use_sql_comments}
        format_sql: ${jpa.properties.hibernate.format_sql}

###
#   H2 Settings
###
  h2:
    console:
      enabled: ${h2.console.enable}
      path: ${h2.console.path}
      settings:
        trace: ${h2.console.settings.trace}
        web-allow-others: ${h2.console.settings.web.allow.others}

###
#   Logging Settings
###
logging:
    level:
      root: ${logging.level.root}
      web: ${logging.level.web}
      org.hibernate: ${logging.level.hibernate}