SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS CHURCH;
DROP TABLE IF EXISTS CAMPAIGN;
DROP TABLE IF EXISTS CONTRIBUTOR;
DROP TABLE IF EXISTS PROVING_TYPE;
DROP TABLE IF EXISTS CONTRIBUTION;
DROP TABLE IF EXISTS BEAD;
DROP TABLE IF EXISTS BEAD_CONTRIBUTION;
SET FOREIGN_KEY_CHECKS = 1;

/* CHURCH TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`CHURCH` (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'SEQUENTIAL IDENTIFIER OF A CHURCH.',
  NAME VARCHAR(255) NOT NULL COMMENT 'NAME USED AS THE IDENTIFICATION OF A CHURCH.',
  PRIMARY KEY (ID))
COMMENT = 'TABLE WITH ALL EXISTING CHURCHS.';

/* PROVING_TYPE TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`PROVING_TYPE` (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'SEQUENTIAL IDENTIFIER OF A PROVING TYPE.',
  NAME VARCHAR(255) NOT NULL COMMENT 'NAME USED AS THE IDENTIFICATION OF A PROVING OF PAYMENT .',
  MNEMONIC CHAR(3) NOT NULL COMMENT 'MNEMONIC USED AS THE IDENTIFICATION OF A PROVING OF PAYMENT.',
  PRIMARY KEY (ID),
  CONSTRAINT UK_PROVING_TYPE_MNEMONIC UNIQUE (MNEMONIC))
COMMENT = 'TABLE WITH ALL EXISTING PROVING TYPES.';

/* CAMPAIGN TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`CAMPAIGN` (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'SEQUENTIAL IDENTIFIER OF A CAMPAIGN.',
  ID_CHURCH BIGINT NULL COMMENT 'SEQUENTIAL IDENTIFIER OF A CHURCH.',
  ID_PROVING_TYPE BIGINT NULL COMMENT 'SEQUENTIAL IDENTIFIER OF A PROVING TYPE.',
  NAME VARCHAR(255) NOT NULL COMMENT 'SEQUENTIAL IDENTIFIER OF A CAMPAIGN.',
  CREATION_DATE DATE NOT NULL,
  INITIAL_DATE DATE NULL,
  FINAL_DATE DATE NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_CAMPAIGN_CHURCH FOREIGN KEY (ID_CHURCH) REFERENCES CHURCH(ID),
  CONSTRAINT FK_CONTRIBUTION_PROV_TYPE FOREIGN KEY (ID_PROVING_TYPE) REFERENCES PROVING_TYPE(ID),
  CONSTRAINT UK_CAMPAIGN_NAME UNIQUE (NAME))
COMMENT = 'TABLE WITH ALL EXISTING PROVING TYPES CAMPAIGNS.';

/* CONTRIBUTOR TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`CONTRIBUTOR` (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'SEQUENTIAL IDENTIFIER OF A CONTRIBUTOR.',
  NAME VARCHAR(255) NOT NULL COMMENT 'NAME USED AS THE IDENTIFICATION OF A CONTRIBUTOR.',
  FISCAL_NUMBER BIGINT NULL COMMENT 'THE FISCAL NUMBER OF THE CONTRIBUTOR.',
  GENDER CHAR(6) NOT NULL COMMENT 'THE GENDER OF THE CONTRIBUTOR, WHERE M - MALE AND F - FEMALE.',
  CIVIL_STATE VARCHAR(12) NOT NULL COMMENT 'THE CIVIL STATE OF THE CONTRIBUTOR. THE POSSIBLE VALUES ARE: SINGLE, MARRIED, STABLE UNION, DIVORCED AND WIDOWER.',
  ADDRESS VARCHAR(255) NOT NULL COMMENT 'THE ADDRESS WHERE THE CONTRIBUTOR LIVES.',
  BIRTH_DATE DATE NOT NULL COMMENT 'THE BIRTHDAY OF THE CONTRIBUTOR.',
  MARRIAGE_DATE DATE NULL COMMENT 'THE DAY THAT THE CONTRIBUTOR GOT ENGAGED.',
  CREATION_DATE DATE NOT NULL COMMENT 'THE DAT THAT THE CONTRIBUTOR WAS REGISTERED',
  PARTNER_NAME VARCHAR(255) NULL COMMENT 'THE NAME OF THE PARTNER WHO IS MARRIAGE WITH THE CONTRIBUTOR.',
  TELEPHONE BIGINT NULL,
  CELLPHONE BIGINT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UK_CONTRIBUTOR_F_NUMBER UNIQUE (FISCAL_NUMBER))
COMMENT = 'TABLE WITH ALL EXISTING CONTRIBUTORS.';

/* CONTRIBUTION TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`CONTRIBUTION` (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'SEQUENTIAL IDENTIFIER OF A CONTRIBUTION.',
  ID_CAMPAIGN BIGINT NULL COMMENT 'SEQUENTIAL IDENTIFIER OF A CAMPAIGN.',
  ID_CONTRIBUTOR BIGINT NULL COMMENT 'SEQUENTIAL IDENTIFIER OF A CONTRIBUTOR.',
  CREATION_DATE DATE NOT NULL COMMENT 'THE DATE THAT THE CONTRIBUTION WAS REGISTER.',
  AMOUNT BIGINT NOT NULL COMMENT 'THE AMOUNT OF THE CONTRIBUTION IN CENTS.',
  OBSERVATION VARCHAR(255) NULL COMMENT 'THE FIELD TO INSERT SOME OBSERVATION.',
  PRIMARY KEY (ID),
  CONSTRAINT FK_CAMPAIGN_CONTRIBUTION FOREIGN KEY (ID_CAMPAIGN) REFERENCES CAMPAIGN(ID),
  CONSTRAINT FK_CONTRIBUTOR_CONTRIBUTION FOREIGN KEY (ID_CONTRIBUTOR) REFERENCES CONTRIBUTOR(ID))
COMMENT = 'TABLE WITH ALL EXISTING CONTRIBUTIONS.';

/* BEAD_CONTRIBUTION TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`BEAD` (
  ID BIGINT NOT NULL AUTO_INCREMENT COMMENT 'SEQUENTIAL IDENTIFIER OF A BEAD.',
  ID_CAMPAIGN BIGINT NULL COMMENT 'SEQUENTIAL IDENTIFIER OF A CONTRIBUTION.',
  ID_CONTRIBUTOR BIGINT NULL COMMENT 'SEQUENTIAL IDENTIFIER OF A CONTRIBUTOR.',
  IDENTIFICATION_NUMBER VARCHAR(10) NULL COMMENT 'THE IDENTIFICATION NUMBER LOCATED ON THE PHYSICAL BEAD.',
  PRIMARY KEY (ID),
  CONSTRAINT FK_BEAD_CAMPAIGN FOREIGN KEY (ID_CAMPAIGN) REFERENCES CAMPAIGN(ID),
  CONSTRAINT FK_BEAD_CONTRIBUTOR FOREIGN KEY (ID_CONTRIBUTOR) REFERENCES CONTRIBUTOR(ID),
  CONSTRAINT UK_CONTRIBUTOR_CAMP_BEAD UNIQUE (ID_CAMPAIGN, ID_CONTRIBUTOR))
COMMENT = 'TABLE WITH ALL EXISTING BEADS.';

/* BEAD_CONTRIBUTION TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`BEAD_CONTRIBUTION` (
  ID_BEAD BIGINT NULL COMMENT 'SEQUENTIAL IDENTIFIER OF A RELATIONSHIP BETWEEN A BEAD AND ITS CONTRIBUTIONS.',
  ID_CONTRIBUTION BIGINT NULL COMMENT 'SEQUENTIAL IDENTIFIER OF A CONTRIBUTION.',
  CONSTRAINT FK_BEAD_CONTRIBUTION FOREIGN KEY (ID_BEAD) REFERENCES BEAD(ID),
  CONSTRAINT FK_CONTRIBUTION_BEAD FOREIGN KEY (ID_CONTRIBUTION) REFERENCES CONTRIBUTION(ID),
  CONSTRAINT UK_BEAD_CONTRIBUTION UNIQUE (ID_BEAD, ID_CONTRIBUTION))
COMMENT = 'TABLE WITH ALL EXISTING CONTRIBUTIONS ASSOCIATED TO ALL BEADS.';
