SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS IGREJA;
DROP TABLE IF EXISTS CAMPANHA;
DROP TABLE IF EXISTS CONTRIBUINTE;
DROP TABLE IF EXISTS TIPO_COMPROVANTE;
DROP TABLE IF EXISTS CONTRIBUICAO;
DROP TABLE IF EXISTS TALAO;
DROP TABLE IF EXISTS TALAO_CONTRIBUICAO;
SET FOREIGN_KEY_CHECKS = 1;

/* TABELA IGREJA */
CREATE TABLE `PAYMENT-MANAGEMENT`.`IGREJA` (
  ID   INT          NOT NULL AUTO_INCREMENT
  COMMENT 'IDENTIFICADOR SEQUENCIAL DE IGREJA.',
  NOME VARCHAR(255) NOT NULL
  COMMENT 'NOME UTILIZADO PARA A IDENTIFICAÇÃO DA IGREJA.',
  PRIMARY KEY (ID)
)
  COMMENT = 'TABELA COM AS IGREJAS EXISTENTES.';

/* TABELA TIPO_COMPROVANTE  */
CREATE TABLE `PAYMENT-MANAGEMENT`.`TIPO_COMPROVANTE` (
  ID    INT          NOT NULL AUTO_INCREMENT
  COMMENT 'IDENTIFICADOR SEQUENCIAL DE UM TIPO DE COMPROVANTE.',
  NOME  VARCHAR(255) NOT NULL
  COMMENT 'NOME UTILIZADO PARA A IDENTIFICAÇÃO DO COMPROVANTE.',
  SIGLA CHAR(3)      NOT NULL
  COMMENT 'SIGLA UTILIZADA PARA A IDENTIFICAÇÃO DO COMPROVANTE.',
  PRIMARY KEY (ID),
  CONSTRAINT UK_TIPO_COMPROVANTE_SIGLA UNIQUE (SIGLA)
)
  COMMENT = 'TABELA DE POSSIVEIS TIPOS DE COMPROVANTES.';

/* TABELA CAMPANHA  */
CREATE TABLE `PAYMENT-MANAGEMENT`.`CAMPANHA` (
  ID                  INT          NOT NULL AUTO_INCREMENT
  COMMENT 'IDENTIFICADOR SEQUENCIAL DE UMA CAMPANHA.',
  ID_IGREJA           INT          NOT NULL
  COMMENT 'IDENTIFICADOR SEQUENCIAL DA IGREJA PORTADORA DA CAMPANHA',
  ID_TIPO_COMPROVANTE INT          NOT NULL
  COMMENT 'IDENTIFICADOR DO TIPO DE COMPROVANTE UTILIZADO PARA NO REGISTRO DO PAGAMENTO.',
  NOME                VARCHAR(255) NOT NULL
  COMMENT 'IDENTIFICADOR SEQUENCIAL DE UMA CAMPANHA.',
  DATA_CRIACAO        DATE         NOT NULL,
  DATA_INICIO         DATE         NOT NULL,
  DATA_FIM            DATE         NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT FK_CAMPANHA_IGREJA FOREIGN KEY (ID_IGREJA) REFERENCES IGREJA (ID),
  CONSTRAINT FK_CONTRIBUICAO_TIPO_COMP FOREIGN KEY (ID_TIPO_COMPROVANTE) REFERENCES TIPO_COMPROVANTE (ID)
)
  COMMENT = 'TABELA ONDE TODAS AS CAMPANHAS SERÃO CATALOGADAS.';

/* TABELA CONTRIBUINTE  */
CREATE TABLE `PAYMENT-MANAGEMENT`.`CONTRIBUINTE` (
  ID              INT          NOT NULL AUTO_INCREMENT
  COMMENT 'IDENTIFICADOR SEQUENCIAL DE UM CONTRIBUINTE.',
  NOME            VARCHAR(255) NOT NULL
  COMMENT 'NOME PARA IDENTIFICAÇÃO DO CONTRIBUINTE.',
  CPF             INT          NOT NULL
  COMMENT 'IDENTIFICADOR FISCAL DO CONTRIBUINTE.',
  SEXO            CHAR(1)      NOT NULL
  COMMENT 'GÊNERO SEXUAL DO CONTRIBUINTE, ONDE TEMOS M - MASCULINO E F - FEMININO.',
  ESTADO_CIVIL    VARCHAR(50)  NOT NULL
  COMMENT 'ESTADO CIVIL DO CONTRIBUINTE, ONDE TEMOS OS POSSÍVEIS VALORES: SOLTEIRO, CASADO, UNIÃO ESTÁVEL, DIVORCIADO E VIÚVO.',
  ENDERECO        VARCHAR(255) NOT NULL
  COMMENT 'ENDEREÇO RESIDENCIAL DO CONTRIBUINTE.',
  DATA_NASCIMENTO DATE         NOT NULL
  COMMENT 'DATA DE NASCIMENTO DO CONTRIBUINTE.',
  DATA_CASAMENTO  DATE         NULL
  COMMENT 'DATA DE CASAMENTO DO CONTRIBUINTE.',
  NOME_CONJUGUE   VARCHAR(255) NULL
  COMMENT 'DATA DE CASAMENTO DO CONTRIBUINTE.',
  CELULAR         INT          NULL,
  PRIMARY KEY (ID),
  CONSTRAINT UK_CONTRIBUINTE_CPF UNIQUE (CPF)
)
  COMMENT = 'TABELA REPRESENTANTE DOS DADOS DE DETERMINADO CONTRIBUINTE.';

/* TABELA CONTRIBUICAO  */
CREATE TABLE `PAYMENT-MANAGEMENT`.`CONTRIBUICAO` (
  ID              INT  NOT NULL AUTO_INCREMENT
  COMMENT 'IDENTIFICADOR SEQUENCIAL DE UMA CONTRIBUIÇÃO.',
  ID_CAMPANHA     INT  NOT NULL
  COMMENT 'IDENTIFICADOR SEQUENCIAL DE UMA CONTRIBUIÇÃO.',
  ID_CONTRIBUINTE INT  NOT NULL
  COMMENT 'IDENTIFICADOR DO CONTRIBUINTE QUE EFETUOU O PAGAMENTO.',
  DATA_LANCAMENTO DATE NOT NULL
  COMMENT 'DATA EM QUE OCORREU A CONTRIBUIÇÃO.',
  VALOR           INT  NOT NULL
  COMMENT 'VALOR EM CENTAVOS DA CONTRIBUIÇÃO.',
  PRIMARY KEY (ID),
  CONSTRAINT FK_CAMPANHA_CONTRIBUICAO FOREIGN KEY (ID_CAMPANHA) REFERENCES CAMPANHA (ID),
  CONSTRAINT FK_CONTRIBUINTE_CONTRIBUICAO FOREIGN KEY (ID_CONTRIBUINTE) REFERENCES CONTRIBUINTE (ID)
)
  COMMENT = 'TABELA DE CONTRBUIÇÕES EFETUADOS POR CAMAPANHA E QUE ESTÃO ASSOCIADAS A DETERMINADO CONTRIBUINTE.';

/* TABELA TALAO_CONTRIBUICAO */
CREATE TABLE `PAYMENT-MANAGEMENT`.`TALAO` (
  ID                   INT NOT NULL AUTO_INCREMENT
  COMMENT 'IDENTIFICADOR SEQUENCIAL DE UM TALÃO.',
  ID_CAMPANHA          INT NOT NULL
  COMMENT 'IDENTIFICADOR SEQUENCIAL DE UMA CONTRIBUIÇÃO.',
  ID_CONTRIBUINTE      INT NOT NULL
  COMMENT 'IDENTIFICADOR DO CONTRIBUINTE QUE EFETUOU O PAGAMENTO.',
  NUMERO_IDENTIFICACAO INT NOT NULL
  COMMENT 'NÚMERO IDENTIFICADOR LOCALIZADO NO TALÃO FÍSICO.',
  PRIMARY KEY (ID),
  CONSTRAINT FK_TALAO_CAMPANHA FOREIGN KEY (ID_CAMPANHA) REFERENCES CAMPANHA (ID),
  CONSTRAINT FK_TALAO_CONTRIBUINTE FOREIGN KEY (ID_CONTRIBUINTE) REFERENCES CONTRIBUINTE (ID),
  CONSTRAINT UK_CONTRIBUINTE_CAMP_TALAO UNIQUE (ID_CAMPANHA, ID_CONTRIBUINTE)
)
  COMMENT = 'TABELA UTILIZADA COMO REPRESENTANTE DE UM TALAO UTILIZADO POR DETERMINADO CONTRIBUINTE EM UMA CAMPANHA ESPECIFICA.';

/* TABELA TALAO_CONTRIBUICAO */
CREATE TABLE `PAYMENT-MANAGEMENT`.`TALAO_CONTRIBUICAO` (
  ID_TALAO        INT NOT NULL
  COMMENT 'IDENTIFICADOR DO TALÃO ONDE SERÃO REGISTRADAS AS CONTRIBUIÇÕES.',
  ID_CONTRIBUICAO INT NOT NULL
  COMMENT 'IDENTIFICADOR DA CONTRIBUIÇÃO ASSOCIADA A DETERMINADO TALÃO.',
  CONSTRAINT FK_TALAO_CONTRIBUICAO FOREIGN KEY (ID_TALAO) REFERENCES TALAO (ID),
  CONSTRAINT FK_CONTRIBUICAO_TALAO FOREIGN KEY (ID_CONTRIBUICAO) REFERENCES CONTRIBUICAO (ID),
  CONSTRAINT UK_TALAO_CONTRIBUICAO UNIQUE (ID_TALAO, ID_CONTRIBUICAO)
)
  COMMENT = 'TABELA UTILIZADA PARA ASSOCIAR DETERMINADA CONTRIBUICAO COM UM TALAO ESPECIFICO.';
