INSERT INTO `PAYMENT-MANAGEMENT`.`PROVING_TYPE` (`NAME`, `MNEMONIC`) VALUES ('TALÃO', 'TLO');
INSERT INTO `PAYMENT-MANAGEMENT`.`PROVING_TYPE` (`NAME`, `MNEMONIC`) VALUES ('SEM COMPROVANTE', 'SCT');
COMMIT;
