INSERT INTO `PAYMENT-MANAGEMENT`.`TIPO_COMPROVANTE` (`NOME`, `SIGLA`) VALUES ('TALÃO', 'TLO');
INSERT INTO `PAYMENT-MANAGEMENT`.`TIPO_COMPROVANTE` (`NOME`, `SIGLA`) VALUES ('SEM COMPROVANTE', 'SCT');
COMMIT;
