/*EDICAO e LANCAMENTO - POIS PRIMEIRO DEVE-SE RECUPERAR O CONTRIBUINTE ATRAVES DA CAMPANHA E TALAO*/
SELECT BEAD.IDENTIFICATION_NUMBER, CAMPAIGN.NAME AS CAMPAIGN, CONTRIBUTOR.NAME, CONTRIBUTION.AMOUNT, CONTRIBUTION.CREATION_DATE
FROM BEAD
JOIN CONTRIBUTOR ON BEAD.ID_CONTRIBUTOR = CONTRIBUTOR.ID
JOIN CAMPAIGN ON CAMPAIGN.ID = BEAD.ID_CAMPAIGN
JOIN CONTRIBUTION ON CONTRIBUTION.ID_CONTRIBUTOR = BEAD.ID_CONTRIBUTOR
WHERE BEAD.IDENTIFICATION_NUMBER = 10
AND CAMPAIGN.ID = 1;

/*INSERT*/