/* INSERT INTO ROLE TABLE */
INSERT INTO `PAYMENT-MANAGEMENT`.`ROLE` (ROLE) VALUES ('ADMIN');

/* INSERT INTO USER TABLE
   LOGIN: SAOJOAQUIM AND PASSWORD: SAOJOAQUIM */
INSERT INTO `PAYMENT-MANAGEMENT`.`USER` (`USERNAME`,`PASSWORD`,`NAME`,`LAST_NAME`,`ACTIVE`) VALUES ('saojoaquim','$2a$10$dhRI0IRUpGMijNNMB8/x1eOBizpt6SO2JveLLuf/NOxEsqVpyhkJa','SÃO JOAQUIM','',1);

/* INSERT INTO USER_ROLE */
INSERT INTO `PAYMENT-MANAGEMENT`.`USER_ROLE` (`ID_USER`,`ID_ROLE`) VALUES ((SELECT ID FROM USER WHERE USERNAME = 'saojoaquim'),(SELECT ID FROM ROLE WHERE ROLE = 'ADMIN'));
COMMIT;