SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `ROLE`;
DROP TABLE IF EXISTS `USER`;
DROP TABLE IF EXISTS `USER_ROLE`;
SET FOREIGN_KEY_CHECKS = 1;

/* ROLE TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`ROLE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ROLE` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

/* USER TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`USER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `NAME` VARCHAR(255) NOT NULL,
  `LAST_NAME` VARCHAR(255) NOT NULL,
  `ACTIVE` INT(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

/* USER_ROLE TABLE */
CREATE TABLE `PAYMENT-MANAGEMENT`.`USER_ROLE` (
  `ID_USER` INT(11) NOT NULL,
  `ID_ROLE` INT(11) NOT NULL,
  PRIMARY KEY (`ID_USER`,`ID_ROLE`),
  CONSTRAINT FK_USER_ROLE FOREIGN KEY (ID_USER) REFERENCES `USER`(ID),
  CONSTRAINT FK_ROLE_USER FOREIGN KEY (ID_ROLE) REFERENCES `ROLE`(ID),
  CONSTRAINT UK_USER_ROLE UNIQUE (ID_USER, ID_ROLE)
);