# ==============
# = Data Source
# ==============
spring:
  datasource:
    url: @datasource.url@
    platform: @datasource.platform@
    username: @datasource.username@
    password: @datasource.password@
    driverClassName: @datasource.driver@

# ===================
# = Spring Data Rest
# ===================
  data:
      rest:
        basePath: api

# ==================
# = Jpa / Hibernate
# ==================
  jpa:
    database-platform: @jpa.database.platform@
    hibernate:
      ddl-auto: @jpa.hibernate.dll.auto@
    properties:
      hibernate:
        show_sql: @jpa.properties.hibernate.show_sql@
        use_sql_comments: @jpa.properties.hibernate.use_sql_comments@
        format_sql: @jpa.properties.hibernate.format_sql@

# ===============================
# = Thymeleaf configurations
# ===============================
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

# ==============================================================
# = Spring Security / Queries for AuthenticationManagerBuilder
# ==============================================================
  security:
    ignoredUrl: /build/**
    role:
      admin:
        mnemonic: ADMIN
        securedPageUrl: /pages/**
        securedApiUrl: /api/**
    login:
      url: /login
      errorUrl: /login?error
      successUrl: /
      accessDeniedUrl: /errors/403
    logout:
      url: /api/logout
    queries:
      users: SELECT USERNAME, PASSWORD, ACTIVE FROM USER WHERE USERNAME=?
      roles: SELECT U.USERNAME, R.ROLE FROM USER U INNER JOIN USER_ROLE UR ON(U.ID=UR.ID_USER) INNER JOIN ROLE R ON(UR.ID_ROLE=R.ID) WHERE U.USERNAME=?

# ==================
# = Server settings
# ==================
server:
  port: 8081
  contextPath: /payment-management

# ==============
# = H2 settings
# ==============
  h2:
    console:
      enabled: @h2.console.enable@
      path: /console
      settings:
        trace: false
        web-allow-others: false

# ===================
# = Logging Settings
# ===================
logging:
    level:
      root: @logging.level.root@
      web: @logging.level.web@
      org.hibernate: @logging.level.hibernate@