###
#   Database Settings
###
spring:
  data:
    rest:
      basePath: api
  datasource:
    url: @datasource.url@
    platform: @datasource.platform@
    username: @datasource.username@
    password: @datasource.password@
    driverClassName: @datasource.driver@
  jpa:
    database-platform: @jpa.database.platform@
    hibernate:
      ddl-auto: @jpa.hibernate.dll.auto@
    properties:
      hibernate:
        show_sql: @jpa.properties.hibernate.show_sql@
        use_sql_comments: @jpa.properties.hibernate.use_sql_comments@
        format_sql: @jpa.properties.hibernate.format_sql@
  thymeleaf:
    mode: LEGACYHTML5

###
#   Server Settings
###
server:
  port: 8081
  contextPath: /payment-management

###
#   H2 Settings
###
  h2:
    console:
      enabled: @h2.console.enable@
      path: /console
      settings:
        trace: false
        web-allow-others: false

###
#   Logging Settings
###
logging:
    level:
      root: @logging.level.root@
      web: @logging.level.web@
      org.hibernate: @logging.level.hibernate@