/* INSERT INITIAL DATA FOR CHURCH. */
INSERT INTO `CHURCH` (`NAME`) VALUES ('PARÓQUIA SÃO JOAQUIM');

/* INSERT INITIAL DATA FOR PROVING TYPE */
INSERT INTO `PROVING_TYPE` (`NAME`, `MNEMONIC`) VALUES ('TALÃO', 'TLO');
INSERT INTO `PROVING_TYPE` (`NAME`, `MNEMONIC`) VALUES ('SEM COMPROVANTE', 'SCT');

/* INSERT INITIAL DATA FOR ROLE. */
INSERT INTO `ROLE` (ROLE) VALUES ('ADMIN');

/* INSERT INITIAL DATA FOR USER.
   LOGIN: SAOJOAQUIM AND PASSWORD: SAOJOAQUIM */
INSERT INTO `USER` (`USERNAME`,`PASSWORD`,`NAME`,`LAST_NAME`,`ACTIVE`) VALUES ('saojoaquim','$2a$10$dhRI0IRUpGMijNNMB8/x1eOBizpt6SO2JveLLuf/NOxEsqVpyhkJa','SÃO JOAQUIM','',1);

/* INSERT INITIAL DATA FOR USER ROLE. */
INSERT INTO `USER_ROLE` (`ID_USER`,`ID_ROLE`) VALUES ((SELECT ID FROM USER WHERE USERNAME = 'saojoaquim'),(SELECT ID FROM ROLE WHERE ROLE = 'ADMIN'));