SELECT CONTRIBUTOR.ID, CONTRIBUTOR.NAME, 
CONTRIBUTOR.BIRTH_DATE, 
IFNULL(CONTRIBUTOR.MARRIAGE_DATE,'-') AS MARRIAGE_DATE, 
CAMPAIGN.NAME, 
CONTRIBUTION.CREATION_DATE, 
CONTRIBUTION.AMOUNT/100
FROM CONTRIBUTOR
JOIN CONTRIBUTION ON CONTRIBUTION.ID_CONTRIBUTOR = CONTRIBUTOR.ID
JOIN CAMPAIGN ON CAMPAIGN.ID = CONTRIBUTION.ID_CAMPAIGN

WHERE CAMPAIGN.NAME LIKE '%A%' 
AND CONTRIBUTION.CREATION_DATE BETWEEN '2017-01-18' AND '2018-01-18'
/*Comemoracao deve-se ser tratado no java, caso a data de casamento ou aniversario esteja dentro do mes atual
pode acontecer de ser aniversario e casamento no mesmo mês*/;
