/*LISTAGEM CONTRIBUINTES*/
SELECT CONTRIBUTOR.ID, CONTRIBUTOR.NAME, BEAD.IDENTIFICATION_NUMBER AS BEAD, CAMPAIGN.NAME
FROM CONTRIBUTOR
INNER JOIN BEAD ON BEAD.ID_CONTRIBUTOR = CONTRIBUTOR.ID
INNER JOIN CAMPAIGN ON  CAMPAIGN.ID = BEAD.ID_CAMPAIGN

WHERE CONTRIBUTOR.NAME LIKE '%O%'
AND CAMPAIGN.NAME = 'DIZIMO'
AND BEAD.IDENTIFICATION_NUMBER = 1
ORDER BY CONTRIBUTOR.CREATION_DATE DESC;

/*EDICAO CONTRIBUINTE*/
SELECT * FROM CONTRIBUTOR WHERE ID = 1;

/*OBTEM TABELA TALAO*/
SELECT BEAD.IDENTIFICATION_NUMBER AS BEAD, CAMPAIGN.NAME, COUNT(CONTRIBUTION.AMOUNT) AS COUNT, SUM(CONTRIBUTION.AMOUNT)
FROM BEAD
JOIN CAMPAIGN ON CAMPAIGN.ID = BEAD.ID_CAMPAIGN
LEFT JOIN BEAD_CONTRIBUTION ON BEAD_CONTRIBUTION.ID_BEAD = BEAD.ID
LEFT JOIN CONTRIBUTION ON BEAD_CONTRIBUTION.ID_CONTRIBUTION = CONTRIBUTION.ID AND CONTRIBUTION.ID_CAMPAIGN = CAMPAIGN.ID
WHERE BEAD.ID_CONTRIBUTOR = 1
GROUP BY BEAD.IDENTIFICATION_NUMBER, CAMPAIGN.NAME;

/*EDITAR TALAO*/
SELECT * FROM BEAD WHERE ID = 1;

/*CRIACAO CONTRIBUINTE*/
INSERT INTO CONTRIBUTOR VALUES (ID ,NAME ,FISCAL_NUMBER ,GENDER ,CIVIL_STATE ,ADDRESS ,BIRTH_DATE ,MARRIAGE_DATE ,CREATION_DATE ,PARTNER_NAME ,TELEPHONE ,CELLPHONE );

/*CRIACAO TALAO*/
INSERT INTO BEAD VALUES ('ID','CAMPANHA', 'IDCONTRIBUTOR','IDENTIFICATIONNUMBER');