/*LISTAGEM CAMPANHA*/
SELECT ID, NAME FROM CAMPAIGN
WHERE CAMPAIGN.NAME LIKE '%A%' 
ORDER BY CREATION_DATE DESC;

/*EDICAO CAMPANHA*/
SELECT * FROM CAMPAIGN WHERE ID = 1;

/*INSERT CAMPANHA*/
INSERT INTO CAMPAIGN VALUES ('ID','ID_CHURCH','ID_PROVING_TYPE','NAME','CREATION_DATE','INITIAL_DATE','FINAL_DATE');
